export const login: string = '/login';
export const logout: string = '/logout';
export const newPass: string = '/newPassword';
export const profile: string = '/profile';
export const cards: string = '/cards';
export const restorePass: string = '/restorePassword';
export const registration: string = '/registration';
export const resetPass: string = '/resetPassword'
// export const pageNotFound: string = '/pageNotFound_404';
